name: Update news

# Controls when the workflow will run
on:
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Git config ğŸ”§
        run: |
          git config --global user.name "giscafer"
          git config --global user.email "giscafer@outlook.com"

      - name: Update news
        run: |
          cd server
          yarn install
          cd ..
          node ./server/src/once.js
          ls -l details
      - name: Push changes
        run: |
          git add .
          git commit -m 'chore(ci): Update news'
          git push
