name: Update news

# Controls when the workflow will run
on:
  schedule:
    - cron: '20 * * * *'
  # https://docs.github.com/cn/developers/webhooks-and-events/events/issue-event-types
  # issues:
  #   types:
  #     - opened
  #     - closed
  #     - renamed
  #     - labeled
  #     - unlabeled
  #     - reopened
  #     - committed # ä¿®æ”¹ï¼Ÿ
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Git config ğŸ”§
        run: |
          git config --global user.name "giscafer"
          git config --global user.email "giscafer@outlook.com"

      - name: Update news
        run: |
          cd server
          yarn install
          cd ..
          node ./server/src/once.js
          ls -l
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
